### ISSUE TITLE
 `DISABLE_MD_LINTING` and `DISABLE_MD_LINK_CHECK` are dead variables

### ISSUE THREAD

**Issue by kvmware** [knative/hack#200]
As part of https://github.com/knative/hack/pull/199 those env var are never used, yet littered through out our repos. This should be cleaned up.
https://cs.github.com/?q=org%3Aknative+DISABLE_MD_LINTING

**Comment by kellyaa** [comment]
I think we can close since the mentioned PRs are merged - Agree or disagree  @kvmware  ?

**Comment by kvmware** [comment]
Again thanks for the awesome work! Based on https://github.com/WyriHaximus/github-action-wait-for-status I see that there is a lot of references to that var in test-infra. Once that is purged I think we are good on this issue :+1:

**Comment by kvmware** [comment]
Thanks again!
