### ISSUE TITLE
Signing should respect the ARTIFACTS_TO_PUBLISH variable

### ISSUE THREAD

**Issue by cardil** [knative/hack#240]
The code signing should respect the `ARTIFACTS_TO_PUBLISH` variable. If the variable contains the `checksums.txt` file, that file should be updated.

Current code expects the artifacts to live in project root.

https://github.com/knative/hack/blob/cf1a127cfdcd88b1d74fec195089a2090178a596/release.sh#L316-L359

/kind bug

**Comment by cardil** [comment]
/cc @upodroid 

I can provide a fix for this, but after I finish my other tasks.

**Comment by upodroid** [comment]
Go ahead

**Comment by cardil** [comment]
The https://github.com/knative-sandbox/homebrew-kn-plugins/issues/134 is caused by this.
