### ISSUE TITLE
Darwin artifact signing should look up a checksums file in ARTIFACTS_TO_PUBLISH variable

### ISSUE THREAD

**Issue by cardil** [knative/hack#266]
https://github.com/knative/hack/blob/c7cfcb062de90832da2423d92cd0135706ee07a0/release.sh#L337-L350

The above code should search the `ARTIFACTS_TO_PUBLISH` variable to look for the location of the checksums file. Currently, it expects the checksums to be in the root folder of the project. This is the cause of the https://github.com/knative-sandbox/homebrew-kn-plugins/issues/134 problem.

/kind bug

**Comment by upodroid** [comment]
possible dupe of #240?

**Comment by cardil** [comment]
Right, let's close this in favor of #240 

/close
