### ISSUE TITLE
Add shellcheck linter

### ISSUE THREAD

**Issue by kvmware** [knative/hack#269]
This repo is mostly bash scripts and shellcheck helps us have secure good bash.

Our actions repo has a shellcheck linter reusable github action that should be used.

**Comment by kauana** [comment]
Hey @kvmware,

Do we want to run the action on opened PRs? If so, only on `main` and `release-` branches?

Thanks

**Comment by kvmware** [comment]
Yea, the shellcheck linter and how it should be ran (example) should be in the knative/actions repo.

Thanks for looking into this!

**Comment by kauana** [comment]
@kvmware now that #289 was merged, maybe we can close this issue too?
