### ISSUE TITLE
Add docs for how to setup a repo to include these scripts

### ISSUE THREAD

**Issue by rhuss** [knative/hack#35]
Maybe I just have overlooked, but we should document how to bootstrap a fresh repos that leverages the hack scripts.

Something like;

* Create a file `hacks/tool.go` with the anonymous imports to "knative.dev/hack"
* Run `go mod vendor`

If this is the canonical way for doing the initialisation, then I can create a PR for the README. (But maybe there is another easier way ?)

**Comment by n3wscott** [comment]
The best way might be to start from one of our sample projects: 

https://github.com/knative-sandbox/sample-controller
https://github.com/knative-sandbox/sample-source

**Comment by rhuss** [comment]
True (and we need something similar for kn plugins), but for understanding the mechanics, I think a procedural step-by-step instruction to setup the test-infra scripts (maybe even for alreading existing projects) might have some value.

**Comment by kvmware** [comment]
Is this captured with https://github.com/knative/community/blob/98eac80349758b729dd4e852f86ac05480af6543/.github/ISSUE_TEMPLATE/new-repo.md ?

**Comment by kvmware** [comment]
If not please reopen this issue.
