### ISSUE TITLE
Adding "knative-gcp/test/conflict/" to the caller whitelist for package shell

### ISSUE THREAD

**Issue by cathyzhyi** [knative/hack#41]
I am trying to add an e2e test to detect `knative-gcp` overwriting other installed components https://github.com/google/knative-gcp/pull/1995. This reads the output of `ko apply` and look for the word `configured`. It would be convenient if I can use the `shell` package.

Is it OK to just add the path to https://github.com/knative/hack/blob/d946d255738345317410fe720e6bac9c9e2c677b/shell/project.go#L68 
or are there any suggestions on how  I should do this?

**Comment by cathyzhyi** [comment]
@cardil Hey Chris, do you have any suggestion about this?

**Comment by cardil** [comment]
@n3wscott @vaikas As you can see this code has gated usage of shell scripting from other places.
https://github.com/knative/hack/blob/d946d255738345317410fe720e6bac9c9e2c677b/shell/project.go#L68-L71

But, the question remains. We should not allow over usage of this shell out function. I see there couple solutions:

- Allow adding additional places to use shell out package - this is dangerous as we explicitly didn't want that to grow, but decline from being used
- Advice forking `knative/hack` repo, and use forked modified one, if shell out is required.
- Advice to not use shell outs at all, but rather implement those operations in Golang

I feel like the last one is most reasonable, but on the other hand will require the most work.

**Comment by n3wscott** [comment]
I am ok adding another allow usage entry, but understand it will be replaced on a shortish timeline. @cathyzhyi would you like to make a PR to add that?

**Comment by cathyzhyi** [comment]
@n3wscott @cardil Thanks for the suggestions! Just to make sure I understand the best way forward correctly. It's ok to add another usage entry but we should move to option 3 `not use shell outs at all, but rather implement those operations in Golang` asap right?

**Comment by kvmware** [comment]
Doing a little manual cleanup. If this is still an issue please reopen this issue.
