### ISSUE TITLE
latest_version might not always work in main/master branch

### ISSUE THREAD

**Issue by zhongduo** [knative/hack#45]
The current `latest_version` uses `git describe` to find the latest major and minor version. This is necessary to work with PRs to older release branches. However, when there is a release error and new commits are needed the auto release Prow job will add the release tag to the HEAD of the release branch instead of the root of the branch. As a result, `git describe` in master/main cannot find the release tag using `git describe`. For example, event 0.20 is released in eventing-kafka, `git describe` will show `0.19`, which will break the upgrade test or any tests depending on this function.

**Comment by n3wscott** [comment]
This seems to be a bug in the prow job, not the method for getting the version:

```
(╯°□°)╯︵  git status
On branch master
Your branch is ahead of 'origin/master' by 226 commits.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean
[08:01:03] snichols@snichols-a03 ~/go/src/github.com/knative/serving (m)
(╯°□°)╯︵  git describe
v0.20.0-30-g80321c486
```

perhaps prow does not have a full checkout?

**Comment by zhongduo** [comment]
IMO the release prow job is doing what it is expected to do. The responsibility is in the developers to make sure when a new release branch is cut, 1) there is no commit added to the release branch before the release bot runs and 2) the release process will not fail. 

This is no easy way to make `git describe` in master works if there is a problem in the release process. Unfortunately the likelihood of failing this is high, considering the number of repos knative has.

**Comment by zhongduo** [comment]
Another possible solution is to change the release Prow job so that it can detects a new release tag and cut the release branch automatically. But I expect changing the latest_version is easier than the Prow process.... Note the the proposed change will only affect the master/main.

**Comment by coryrc** [comment]
Sorry, I still don't get it. Can you supply an example of the tag it currently calculates in the good and bad case, and an example of what it will be after?

**Comment by zhongduo** [comment]
Try running this in `eventing-kafka`, it will report that the latest
version is 0.19.x. In other repos that do the release properly, it should
be 0.20.x.

**Comment by coryrc** [comment]
If there's not a 0.20 release isn't 0.19.x the appropriate response?

**Comment by zhongduo** [comment]
> If there's not a 0.20 release isn't 0.19.x the appropriate response?

But 0.20 branch is already cut in `evneint-kafka`. The problem is that it is not tagged in a commit in master branch due to error in the release process.

**Comment by coryrc** [comment]
I'm trying to understand why it matters. Once you finish the release and tag properly, it will begin using `0.20`. Until then it seems to be doing the right thing: using the last release.

`new commits are needed the auto release Prow job will add the release tag to the HEAD of the release branch instead of the root of the branch.` This sounds like correct behaviour?

`As a result, git describe in master/main cannot find the release tag using git describe` I disagree and believe it's working as it should: it's using the last release `0.19`. The existence of a branch is insufficient to describe a release.

**Comment by zhongduo** [comment]
I think it will make more sense if you look at eventing-kafka now. Release 0.20 is already done: https://github.com/knative-sandbox/eventing-kafka/releases/tag/v0.20.0

There is nothing wrong with the release now. The problem was the tagged commit is only available in the release branch but not the master. So 'git describe` is still showing `v0.19`, but `git tag` will be able to find `v0.20`.
