### ISSUE TITLE
codegen-library.sh doesn't work with run_go_tool

### ISSUE THREAD

**Issue by dprotaso** [knative/hack#63]
1) codegen-library.sh changes GOBIN 
2) run_go_tool installs things into GOBIN
3) GOBIN is not on the path

Thus because 3) isn't done some scripts will actually run things that are on your system path vs. the hermetic GOBIN build.

ie. go-licenses typically is the case I've observed

**Comment by vincent-pli** [comment]
@dprotaso 
Yes, I have hit the same issue, the 
https://github.com/knative/hack/blob/b6ab329907d3ca6c6b90fe223905a7580b66d02a/library.sh#L513

raise `can not found the command`,
so I just add ${GOPATH}/bin/
to workaround it.

**Comment by vincent-pli** [comment]
Could we just quick fix it as the solution i mentioned in last comments? i need a official fix asap, workaround not make sense.

**Comment by dprotaso** [comment]
I think this is resolved via: https://github.com/knative/hack/pull/73
